//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notlar
    {
        public int NotNo { get; set; }
        public Nullable<int> Vize { get; set; }
        public Nullable<int> Final { get; set; }
        public string Durum { get; set; }
        public Nullable<int> DersNo { get; set; }
    
        public virtual Dersler Dersler { get; set; }
    }
}
