//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        public int OgretmenNo { get; set; }
        public string OgretmenAdi { get; set; }
        public string OgretmenSoyadi { get; set; }
        public string Bolum { get; set; }
        public string Unvan { get; set; }
        public Nullable<int> DersNo { get; set; }
    
        public virtual Dersler Dersler { get; set; }
    }
}
