//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public int OgrenciNo { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public string Fakulte { get; set; }
        public string Bolum { get; set; }
        public Nullable<int> Sinif { get; set; }
        public string DanismanHoca { get; set; }
        public Nullable<int> DersNo { get; set; }
    
        public virtual Dersler Dersler { get; set; }
    }
}
